global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: INFO
api:
  dashboard: false
  insecure: false

certificatesresolvers:
  letsencrypt:
    acme:
      tlschallenge: true
      storage: /letsencrypt/acme.json
      # email: NOTE: This is added from docker-compose

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    asDefault: true
    http:
      tls:
        certresolver: letsencrypt

providers:
  file:
    filename: "/etc/traefik/dynamic.yaml"
    watch: true
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: traefik-proxy
    exposedByDefault: false
