services:
  traefik-proxy:
    image: traefik:v3.6
    restart: unless-stopped
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      # - "127.0.0.1:8080:8080"  # The Web UI (enabled by traefik.yaml:api.insecure=true)
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      # Dynamic configs
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL?error}
    volumes:
      # Config
      - ./config/:/etc/traefik/:ro
      # Data
      - ./data/letsencrypt:/letsencrypt
      # System
      # -- Time
      - /etc/localtime:/etc/localtime:ro
      # -- Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-proxy

networks:
  # Use this to create this `docker network create traefik-proxy`
  traefik-proxy:
    external: true
