---
- name: Docker setup
  hosts: localhost
  become: true

  tasks:
    - name: Get original user (before become)
      command: whoami
      register: original_user
      become: false
      changed_when: false

    # System packages
    - name: apt-get update
      ansible.builtin.apt:
        update_cache: yes

    - name: Install required packages
      ansible.builtin.apt:
        state: present
        name:
          - ca-certificates
          - curl

    - name: Add Docker apt repository using deb822_repository
      ansible.builtin.deb822_repository:
        name: docker
        types: deb
        uris: https://download.docker.com/linux/ubuntu
        signed_by: https://download.docker.com/linux/ubuntu/gpg
        components: [stable]
        architectures: "amd64"
        suites: ["{{ ansible_distribution_release }}"]
        enabled: true
        state: present

    - name: Install docker
      ansible.builtin.apt:
        state: present
        update_cache: true
        name:
          - docker-ce

    - name: "add the user {{  original_user.stdout  }} to the docker group"
      user:
        name: "{{  original_user.stdout  }}"
        groups: docker
        append: yes

    # Docker config
    - name: Create /etc/docker directory if it does not exist
      file:
        path: /etc/docker
        state: directory
        mode: '0755'

    - name: set default max logs size and set logs rotation
      copy:
        dest: '/etc/docker/daemon.json'
        content: |
          {
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "1g",
              "max-file": "5"
            }
          }

    # Start
    - name: enable and start docker
      systemd:
        name: docker
        enabled: yes
        state: started
