---
- name: Allow current user to use sudo without a password
  hosts: localhost
  become: true

  tasks:
    - name: Get original user (before become)
      command: whoami
      register: original_user
      become: false
      changed_when: false

    - name: Create sudoers file for passwordless sudo
      copy:
        dest: "/etc/sudoers.d/{{ original_user.stdout }}"
        content: "{{ original_user.stdout }} ALL=(ALL) NOPASSWD:ALL"
        owner: root
        group: root
        mode: '0440'
      notify: Validate sudoers file

  handlers:
    - name: Validate sudoers file
      command: visudo -cf /etc/sudoers.d/{{ original_user.stdout }}
